config/routes.rb
Rails.application.routes.draw do
  
  namespace :admins do
  end
  devise_for :admins, :controllers => {
    :sessions => 'admins/sessions'
  }
  devise_for :customers, :controllers => {
        :sessions => 'customers/sessions',
        :registrations => 'customers/registrations'
  }
  
  scope module: :customers do
    root "homes#top"
    get "homes/about" => "homes#about"
    # 商品
    resources :items, only: [:show, :index]
    get 'genres/:id/genre_items' => 'items#genre_items'
    # 注文
    get "orders/confirm_order" => "orders#confirm_order"
    get "orders/thanks" => "orders#thanks"
    resources :orders, only: [:new, :show, :create, :index]
    # 会員
    get "confirm" => "customers#confirm"
    patch 'customers/withdraw' => 'customers#withdraw', as: 'customers_withdraw'
    resources :customers, only: [:show, :edit, :update]
    # カート
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:create, :index, :update, :destroy]
    # 登録先住所
    resources :addresses, only: [:new, :create, :edit, :update, :destroy]
  end
  
  namespace :admins do
    # 商品
    resources :items, only: [:new, :show, :create, :edit, :index, :update]
    # 注文
    get "/admin" => "homes#top"
    patch "orders/sales_order_status" => "orders#sales_order_status_update"
    patch "orders/production_status" => "orders#production_status_update"
    resources :orders, only: [:show, :index]
    # ジャンル
    resources :genres, only: [:create, :index, :update, :edit]
    # カート
    resources :cart_items, only: [:update]
    # 会員
    resources :customers, only: [:show, :index, :edit, :update, :destroy]
    # 検索
    get 'search' => 'searches#search'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :cart_items
  has_many :addresses
  has_many :orders
  
  enum is_active: { '有効': true, '退会済': false }
  
  def active_for_authentication?
    super && self.is_active == '有効'
  end
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_items
    belongs_to :customer
    has_many :addresses
    
    OrderItem.all.sum(:price)
    enum sales_order_status:{入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4}
end

app/controllers/admins/customers_controller.rb
class Admins::CustomersController < ApplicationController
  
  before_action :authenticate_admin!

  def index
    @customers = Customer.all
    
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:success] = "個人情報を編集しました"
      redirect_to admins_customer_path(@customer)
    else
      flash[:danger] ="個人情報の編集に失敗しました"
      render :edit
    end
  end
  
  private
  
  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :telephone_number, :postal_code, :address, :deleted_at)
  end
  
end

app/controllers/admins/orders_controller.rb
class Admins::OrdersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @orders = Order.page(params[:page]).per(10)
  end

  def show
    @order = Order.find(params[:id])
    @order_items = @order.order_items.all
    # 下記３行は商品合計を出すため
    @sum = 0
    @subtotals = @order_items.map { |order_item| order_item.price * order_item.amount }
    @sum = @subtotals.sum
  end

  # 実装不可でした。
  def sales_order_status_update
    @order = Order.find(params[:order][:id])
    @order.update(order_params)
    flash[:success] = "注文ステータスを更新しました"
    # sales_order_status_is_deposited?(@order)
    redirect_to admins_order_path(@order)
  end

  # 実装不可でした。
  def production_status_update
    @order_item = OrderItem.find(params[:order_item][:id])
    @order_item.update(order_item_params)
    flash[:info] = "製作ステータスを更新しました"
    redirect_to admins_order_path(@order_item.order_id)
  end

  private

  def order_params
    params.require(:order).permit(:sales_order_status)
  end

  def order_item_params
    params.require(:order_item).permit(:production_status)
  end

  # 以下２つは、update時formから送られてくる値がデフォルトでstringなのでintegerに変換するためのもの。まずはそもそも整数にできるか調べる（Integer()で変換できれば数値、例外発生したら違う）
  # def integer_string?(str)
  #   Integer(str)
  #   true
  # rescue ArgumentError
  #   false
  # end

  # def params_int(order_params)
  #   order_params.each do |key, value|
  #     if integer_string?(value)
  #       order_params[key] = value.to_i
  #     end
  #   end
  # end

  # # 注文ステータスが「入金確認」になったら紐づく製作ステータス全てを「製作待ち」に自動更新
  # def sales_order_status_is_deposited?(order)
  #   if order.sales_order_status_before_type_cast == 1
  #     orderorder_items.each do |p|
  #       p.update(item_sales_order_status: 1)
  #     end
  #     flash[:info] = "製作ステータスが「製作待ち」に更新されました"
  #   end
  # end

  # # 製作ステータスが全部「製作完了」になったら注文ステータスが「発送準備中」に自動更新
  # def item_sales_order_status_is_production_complete?(order)
  #   if  order.order_item.all? do |p|
  #         p.item_sales_order_status_before_type_cast == 3
  #       end
  #     order.update(sales_order_status: 3)
  #     flash[:success] = "注文ステータスが「発送準備中」に更新されました"
  #   end
  # end

  # # 製作ステータスが一つでも「製作中」になったら注文ステータスが「製作中」に自動更新
  # def item_sales_order_status_is_in_production?(order_item)
  #   if item_sales_order.item_sales_order_status_before_type_cast == 2
  #     order_item.order.update(sales_order_status: 2)
  #     flash[:success] = "注文ステータスが「製作中」に更新されました"
  #   end
  # end
end

app/controllers/customers/addresses_controller.rb
class Customers::AddressesController < ApplicationController

  def new
      @address = Address.new
      @addresses = Address.all
  end

  def edit
      @address = Address.find(params[:id])
  end

  def create
    address = Address.new(address_params)
    address.customer_id = current_customer.id
    if address.save
      flash[:success] = '配送先を登録しました'
      redirect_to new_address_path
    else
      flash[:danger] = '必要情報を入力してください／ハイフンは使用できません'
      redirect_to new_address_path
    end
  end

  def update
    address = Address.find(params[:id])
    if address.update(address_params)
      flash[:success] = '編集を保存しました'
      redirect_to new_address_path
    else
      @address = Address.find(params[:id])
      flash[:danger] = '必要情報を入力してください／ハイフンは使用できません'
      render "customer/addresses/edit"
    end
  end

  def destroy
      @address = Address.find(params[:id])
      @address.destroy
      flash[:success] = "削除しました"
      redirect_to new_address_path
  end
  
  private
  
  def address_params
      params.require(:address).permit(:postal_code, :address, :name, :id)
      
  end
end

app/controllers/customers/cart_items_controller.rb
class Customers::CartItemsController < ApplicationController
  
  def index
    @cart_items = CartItem.all
  end

  def update
    @cart_item = CartItem.find(params[:id])
    @cart_item.update(cart_items_params)
    redirect_to cart_items_path
  end

  def create
    # @cart_itemを定義（find_byでどの情報のアイテムを持ってくるのかパラメータを参考に記述）
    @cart_item = CartItem.find_by(item_id: params[:cart_item][:item_id], customer_id: current_customer.id)
    if @cart_item.blank?
       @cart_item = CartItem.new(cart_items_params)
       @cart_item.customer_id = current_customer.id
       @cart_item.save
    else
       @cart_item.amount += params[:cart_item][:amount].to_i
       @cart_item.update(amount: @cart_item.amount)
    end
    redirect_to cart_items_path
  end
  
  def destroy
    @cart_item = CartItem.find_by(id: params[:id], customer_id: current_customer.id)
    @cart_item.destroy
    flash[:danger] = "カートから削除しました"
    redirect_to cart_items_path
  end

  def destroy_all
    current_customer.cart_items.destroy_all
    flash[:danger] = "カートが空です"
    redirect_to cart_items_path
  end

  private
  
  

  def cart_items_params
    params.require(:cart_item).permit(:amount, :item_id, :customer_id)
  end
  
  def amount_params
    params.require(:cart_item).permit(:amount)
  end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/customers_controller.rb
class Customers::CustomersController < ApplicationController
    
  def show
      @customer = current_customer
  end
  
  def create
      @customer = Customer.find(params[:id])
  end
    
  def edit
      @customer = Customer.find(params[:id])
  end
  
  def update
      @customer = Customer.find(params[:id])
      if @customer.update(customer_params)
        flash[:success] = "個人情報を編集しました"
        redirect_to customer_path(current_customer.id)
      else
        flash[:danger] = '個人情報の編集に失敗しました'
        render :edit
      end
  end
  
  def confirm
  end

  # 退会アクション
  def withdraw
      @customer = current_customer
      
      @customer.update(is_active: "退会済")
      # ログアウトさせる
      reset_session
      flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
      redirect_to root_path
  end

  private

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :telephone_number, :postal_code, :address, :is_active, :updated_at)
  end
end

app/controllers/customers/homes_controller.rb
class Customers::HomesController < ApplicationController
  
  def top
    @items = Item.all
    @genres = Genre.all
  end

  def about
  end
end

app/controllers/customers/items_controller.rb
class Customers::ItemsController < ApplicationController
  
  def index
    @items = Item.all.page(params[:page])
    @genres = Genre.all
    
  end

  def show
    @item = Item.find(params[:id])
    @genres = Genre.all
  end
  
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/orders_controller.rb
class Customers::OrdersController < ApplicationController
  
  before_action :authenticate_customer!
  
  def new
    @order = Order.new
    @orders = current_customer.cart_items
    @customer = Customer.find(current_customer.id)
    @addresses = @customer.addresses
    @order.save
  end
  
  def show
    @order = Order.find(params[:id])
    @order.freight = 800
    @order_items = @order.order_items.all
  end
  
  def create
    @order = Order.new(order_params)
    @order.save
    current_customer.cart_items.each do |cart_item|
      @order_items = OrderItem.new
      @order_items.amount = cart_item.amount
      @order_items.item_id = cart_item.item_id
      @order_items.order_id = @order.id
      @order_items.price = cart_item.item.price
      @order_items.production_status = 1
      @order_items.save
    end
    @cart_items = current_customer.cart_items
    @cart_items.destroy_all
    redirect_to orders_thanks_path
  end
  
  def index
    @orders = current_customer.orders
  end
  
  def confirm_order
    @orders = current_customer.orders
    @cart_items = current_customer.cart_items
    @sum = @cart_items.sum{|ci| ci.item.price * ci.amount}
    @order = Order.new(order_params)
    @address = Address.all
    
    if params[:selected_address] == "radio1"
      @order.address = current_customer.address
      @order.postal_code = current_customer.postal_code
      @order.name = current_customer.last_name + current_customer.first_name
    elsif params[:selected_address] == "radio2"
      @order.address = Address.find_by(params[:order][:address_for_order]).address
      @order.postal_code = Address.find_by(params[:order][:address_for_order]).postal_code
      @order.name = Address.find_by(params[:order][:address_for_order]).name
    else
      @order = Order.new(order_params)
      @order.save
      
    end
    
  end
  
  def thanks
  end
  
  private
  
  def order_params
    params.require(:order).permit(
      :payment_method, 
      :postal_code, 
      :address,
      :name,
      :customer_id,
      :freight,
      :billing_amount,
      :sales_order_status
    )
  end
  
  def order_item_params
    params.require(:order_item).permit(:order_id, :item_id, :amount, :production_status, :price)
  end
  
  def address_params
      params.require(:address).permit(:postal_code, :address, :name, :id)
      
  end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_active])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  
  def reject_customer
    @customer = Customer.find_by(email: params[:customer][:email].downcase)
    if @customer
      if (@customer.valid_password?(params[:customer][:encrypted_password]) && (@customer.active_for_authentication? == true))
        flash[:error] = "退会済みです。"
        redirect_to new_customer_session_path
      end
    else
      flash[:error] = "必須項目を入力してください。"
    end
    
  end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/customers/orders/confirm_order.html.erb
<h2>注文情報確認</h2>
<div class="row">
    <div class="col-md-7">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">商品名</th>
            <th scope="col">単価（税込）</th>
            <th scope="col">数量</th>
            <th scope="col">小計</th>
          </tr>
        </thead>
        
        <tbody>
          <% @cart_items.each do |cart_item| %>
          <tr>
            <th scope="row"><%= attachment_image_tag(cart_item.item, :image,size: "300x217", fallback: "no_image.jpg") %><%= cart_item.item.name %></th>
            <td><%= cart_item.item.price %></td>
            <td><%= cart_item.amount %></td>
            <td><%= cart_item.item.price * 1.1 * cart_item.amount.to_i %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
      <div class="col-md-5">
        <table class="table">
          <tbody>
            <tr>
              <td>送料</td>
              <td><%= 800 %></td>
            </tr>
            <tr>
              <td>商品合計</td>
              <td><%= @sum %></td>
            </tr>
            <tr>
              <td>請求合計</td>
              <td><%= @sum + 800 %></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
</div>
<h2>支払方法</h2>
<p><%= (@order.payment_method == 0) ? "クレジットカード" : "銀行振り込み" %></p>
<h2>お届け先</h2>
<p><%= @order.postal_code %>&emsp;<%= @order.address %></p>
<p><%= @order.name %></p>
<%= form_with model: @order, url: orders_path, method: :post, local: true do |f| %>
<!--create確認用-->
<%= f.hidden_field :customer_id %>
<%= f.hidden_field :postal_code %>
<%= f.hidden_field :address %>
<%= f.hidden_field :name %>
<%= f.hidden_field :freight %>
<%= f.hidden_field :billing_amount, :value => @sum+800 %>
<%= f.hidden_field :payment_method %>
<%= f.submit "注文を確定する", class:"btn btn-success col-md-3" %>
<% end %>

app/views/customers/orders/index.html.erb
<div class="row login-row">
      <h2>注文履歴一覧</h2>
      <div class="col-xs-10 col-xs-offset-1"style="margin-top: 50px;">
        <table class="table table-bordered">
          <thead>
            <tr class="table-head" style="background-color:#F5F5F5;">
              <th scope="col">注文日</th>
              <th scope="col">配送先</th>
              <th scope="col">注文商品</th>
              <th scope="col">支払金額</th>
              <th scope="col">ステータス</th>
              <th scope="col">注文詳細</th>
            </tr>
          </thead>
          <tbody>
            <% @orders.each do |order| %>
                <tr>
                  <td><%= order.created_at.strftime('%Y/%m/%d') %></td>
                  <td>
                    <p><%= order.postal_code %>&emsp;<%= order.address %></p>
                    <p><%= order.name %></p>
                  </td>
                  <td>
                  <% order.order_items.each do |order_item| %>
                    <p><%= order_item.item.name %></p>
                  <% end %>
                  </td>
                  <td><%= order.billing_amount %>円</td>
                  <td><%= order.sales_order_status %></td>
                  <td>
                  <%= link_to "表示する", order, class: 'btn btn-primary' %>
                  </td>
                </tr>
              <% end %>
          </tbody>
        </table>
      </div>
</div>

app/views/customers/orders/new.html.erb
<div class="row">
    <h2>注文情報入力</h2>
    <div class="col-xs-6" style="margin-top: 50px;">
        <%= form_with model: @order, url: orders_confirm_order_path, method: :get, local: true do |f| %>
        <table class="table">
            <tbody>
                <tr>
                    <th scope="row">支払方法</th>
                    <td>
                        <div class="radio">
                            <%= f.radio_button :payment_method, "0" %>
                            <label class="payment-label">クレジットカード</label>
                            <%= f.radio_button :payment_method, "1" %>
                            <label class="payment-label">銀行振込</label>     
                        </div>
                    </td>
                </tr>
                <tr>
                    <th scope="row">お届け先</th>
                    <td>
                        <div class="radio">
                            <%= radio_button_tag(:selected_address, :radio1) %>
                            <%= label_tag(:selected_address, "ご自身の住所") %>
                            <p><%= @customer.postal_code %><%= @customer.address %></p>
                            <p><%= @customer.first_name %><%= @customer.last_name %></p>
                        </div>
                        <div class="radio">
                            <%= radio_button_tag(:selected_address, :radio2) %>
                            <%= label_tag(:selected_address, "登録済住所から選択") %>
                            <p>
                            <!--ここの記述は正しいのか？-->
                            <%= f.collection_select :address_for_order, @addresses, :id, :postal_code_address_name %>
                            </p>
                        </div>
                        <%= radio_button_tag(:selected_address, :radio3) %>
                        <%= label_tag(:selected_address, "新しいお届け先") %>
                            <div class="field">
                              <label class="postal-code-label">郵便番号(ハイフンなし)</label>
                              <%= f.text_field :postal_code, autofocus: true, class:""%>
                            </div>
                            <div class="field">
                              <label class="address-label">住所</label>
                              <%= f.text_field :address, autofocus: true, class:"", size:"60*60"%>
                            </div>
                             <div class="field">
                            <label class="address-label">宛名</label>
                             <%= f.text_field :name, autofocus: true, class:"", size:"30*30" %>
                            </div>
                    </td>
                </tr>
            </tbody>
        </table>
        <div class="col-xs-offset-5">
            <!--submit-->
        <%= f.submit "注文確認画面に進む", class:"btn btn-primary" %>
        </div>
        <% end %>
    </div>
</div>

app/views/customers/orders/show.html.erb
<div class="container">
    <div class="row">
          <div class="col-md-7">
            <h3>注文履歴詳細</h3>
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">注文日</th>
                    <td style><%= @order.created_at %></td>
                  </tr>
    
                  <tr>
                    <th scope="col">配送先</th>
                    <td style><%= @order.postal_code %>&ensp;<%= @order.address %></td>
                  </tr>
    
                  <tr>
                    <th scope="col">支払方法</th>
                    <td style><%= @order.payment_method %></td>
                  </tr>
    
                  <tr>
                     <th scope="col">ステータス</th>
                     <td style><%= @order.sales_order_status %></td>
                  </tr>
                </thead>
      	    </table>
          </div>
          <div class="col-md-5">
              <h3>請求情報</h3>
              <table class="table">
                <thead>
                  <tr>
                    <th scope="col">商品合計</th>
                    <td style><%= @order.billing_amount - @order.freight %></td>
                  </tr>
    
                  <tr>
                    <th scope="col">配送料</th>
                    <td style><%= @order.freight %></td>
                  </tr>
    
                  <tr>
                    <th scope="col">ご請求額</th>
                    <td style><%= @order.billing_amount %></td>
                  </tr>
                </thead>
      	    </table>
          </div>
    </div>
    <div class="row">
        <h3>注文内容</h3>
            <table class="table table-bordere">
                <thead>
                    <tr>
                        <th>商品</th>
                        <th>単価（税込）</th>
                        <th>個数</th>
                        <th>小計</th>
                    </tr>
                </thead>
                <tbody>
                    <% @order_items.each do |order_item| %>
                    <tr>
                        <td><%= order_item.item.name %></td>
                        <td><%= (order_item.item.price * 1.1).to_i %></td>
                        <td><%= order_item.amount %></td>
                        <td><%= (order_item.price * 1.1).to_i * order_item.amount %></td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/customers/orders/thanks.html.erb
<h3>ご注文ありがとうございました！</h3>