config/routes.rb
Rails.application.routes.draw do
  
  namespace :admins do
  end
  devise_for :admins, :controllers => {
    :sessions => 'admins/sessions'
  }
  devise_for :customers, :controllers => {
        :sessions => 'customers/sessions',
        :registrations => 'customers/registrations'
  }
  
  scope module: :customers do
    root "homes#top"
    get "homes/about" => "homes#about"
    # 商品
    resources :items, only: [:show, :index]
    get 'genres/:id/genre_items' => 'items#genre_items'
    # 注文
    get "orders/confirm_order" => "orders#confirm_order"
    get "orders/thanks" => "orders#thanks"
    resources :orders, only: [:new, :show, :create, :index]
    # 会員
    get "confirm" => "customers#confirm"
    patch 'customers/withdraw' => 'customers#withdraw', as: 'customers_withdraw'
    resources :customers, only: [:show, :edit, :update]
    # カート
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:create, :index, :update, :destroy]
    # 登録先住所
    resources :addresses, only: [:new, :create, :edit, :update, :destroy]
  end
  
  namespace :admins do
    # 商品
    resources :items, only: [:new, :show, :create, :edit, :index, :update]
    # 注文
    get "/admin" => "homes#top"
    patch "orders/sales_order_status" => "orders#sales_order_status_update"
    patch "orders/production_status" => "orders#production_status_update"
    resources :orders, only: [:show, :index]
    # ジャンル
    resources :genres, only: [:create, :index, :update, :edit]
    # カート
    resources :cart_items, only: [:update]
    # 会員
    resources :customers, only: [:show, :index, :edit, :update, :destroy]
    # 検索
    get 'search' => 'searches#search'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
    
belongs_to :genre
has_many :cart_items
has_many :order_items
attachment :image
  
end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController
    
    def index
        @items = Item.all
        
    end
    
    def new
        @item = Item.new
    end
    
    def create
        @item = Item.new(item_params)
        if @item.save
            redirect_to admins_item_path(@item.id)
            flash[:success] = "商品を登録しました"
        else
            flash[:danger] = "必要情報を入力してください"
            render "admins/items/new"
        end
    end
    
    def show
        @item = Item.find(params[:id])
    end
    
    def edit
        @item = Item.find(params[:id])
    end
    
    def update
        @item = Item.find(params[:id])
        if @item.update(item_params)
            redirect_to admins_item_path(@item.id)
            flash[:success] = "商品を更新しました"
        else
            flash[:danger] = "必要情報を入力してください"
            render "admins/items/edit"
        end
    end
    
    private

    def item_params
        params.require(:item).permit(:name, :introduction, :image, :genre_id, :price, :is_active)
    end
end

app/controllers/customers/items_controller.rb
class Customers::ItemsController < ApplicationController
  
  def index
    @items = Item.all.page(params[:page])
    @genres = Genre.all
    
  end

  def show
    @item = Item.find(params[:id])
    @genres = Genre.all
  end
  
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/admins/items/edit.html.erb
<div class="row">
    <h2>商品編集</h2>
    <%= form_with model: @item, url: admins_item_path, method: :patch, local: true do |f| %>
<!-- エラーメッセージ表示-->
    <% if @item.errors.any? %>
    <h3><%= @item.errors.count %>error occurrence</h3>
    <ul>
        <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
    <% end %>
<!-- エラーメッセージ表示-->
    <div class="col-xs-5">
    	<div class="field">
            <%= attachment_image_tag(@item, :image, size: "300x217", fallback: "no_image.jpg") %>
            <%= f.attachment_field :image %>
    	</div>
    </div>
    <div class="col-xs-7">
            <div class="field">
            	<%= f.label :商品名 %>
            	<%= f.text_field :name, class: "form" %>
            </div>
            <div class="field">
            	<%= f.label :商品説明 %>
            	<%= f.text_area :introduction %>
            </div>
            <div class="field">
            	<%= f.label :ジャンル %>
            	<%= f.collection_select(:genre_id, Genre.all, :id, :name, prompt: "選択してください") %>
            </div>
            <div class="field">
            	<%= f.label :税抜価格 %>
            	<%= f.text_field :price %>
            	円
            </div>
            <div class="field">
            	<%= f.radio_button :is_active, true %>
            	<%= f.label :is_active, "販売中" %>
                <%= f.radio_button :is_active, false %>
                <%= f.label :is_active, "売切れ" %>
            </div>
            <div class="actions col-xs-3 col-xs-offset-4">
    		<%= f.submit "変更を保存", class: "btn btn-success glyphicon glyphicon-save" %>
            </div>
        <% end %>
    </div>
</div>

app/views/admins/items/index.html.erb
<h2>商品一覧</h2>
<%= link_to "商品新規登録", new_admins_item_path, class: "btn btn-default" %>
<table class="table table-hover table-inverse">
	<thead>
		<tr>
			<th>商品ID</th>
			<th>商品名</th>
			<th>税抜価格</th>
			<th>ジャンル</th>
			<th>ステータス</th>
		</tr>
	</thead>
	<tbody>
		<% @items.each do |item| %>
			<tr>
				<th><%= item.id %></th>
				<th><%= link_to item.name, admins_item_path(item) %></th>
				<th><%= item.price %></th>
				<th><%= item.genre.name %></th>
				<th><% if item.is_active == true %>
					販売中
					<% else %>
					販売停止中
					<% end %>
				</th>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/admins/items/new.html.erb
<div class="row">
    <h2>商品新規登録</h2>
    <%= form_with model: @item, url: admins_items_path, method: :post, local: true do |f| %>
<!--エラーメッセージ 表示-->
    <% if @item.errors.any? %>
    <h3><%= @item.errors.count %>error occurrence</h3>
    <ul>
        <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
    <% end %>
<!--エラーメッセージ 表示-->
        <div class="col-xs-5">
        	<div class="field">
        		<%= f.label :image %>
                <%= f.attachment_field :image %>
        	</div>
        </div>
        <div class="col-xs-7">
            <div class="field">
            	<%= f.label :商品名 %>
            	<%= f.text_field :name, class: "form" %>
            </div>
            <div class="field">
            	<%= f.label :商品説明 %>
            	<%= f.text_area :introduction %>
            </div>
            <div class="field">
            	<%= f.label :ジャンル %>
            	<%= f.collection_select :genre_id, Genre.all, :id, :name, prompt: "何を選択しますか？" %>
            </div>
            <div class="field">
            	<%= f.label :税抜価格 %>
            	<%= f.text_field :price %>
            	円
            </div>
            <div class="field">
            	<%= f.radio_button :is_active, true %>
            	<%= f.label :is_active, "販売中" %>
                <%= f.radio_button :is_active, false %>
                <%= f.label :is_active, "売切れ" %>
            </div>
            <div class="actions row">
            <%= f.hidden_field :id, :value => @item.id %>
    		<%= f.submit "新規登録",class:"btn btn-primary col-xs-12" %>
            </div>
        </div>
    <% end %>
</div>

app/views/admins/items/show.html.erb
<div class="row">
	<h2>商品詳細</h2>

	<div class="col-xs-5">
		<%= attachment_image_tag(@item, :image,size: "300x217", fallback: "no_image.jpg") %>
	</div>
	<div class="col-xs-7">
		<table class="table">
			<tr>
				<th>商品名</th>
				<th><%= @item.name %></th>
			</tr>
			<tr>
				<th>商品説明</th>
				<th><%= @item.introduction %></th>
			</tr>
			<tr>
				<th>ジャンル</th>
				<th><%= @item.genre.name %></th>
			</tr>
			<tr>
				<th>税込価格（税抜価格）</th>
				<th><%= (@item.price * 1.1).to_i %>(<%= @item.price %>)円</th>
			</tr>
			<tr>
				<th>販売ステータス</th>
				<th>
				<% if @item.is_active == true %>
				販売中
				<% else %>
	            売切れ
				<% end %>
	            </th>
			</tr>
		</table>
		<div>
		<%= link_to '編集する', edit_admins_item_path(@item), class: "btn btn-success glyphicon glyphicon-wrench pull-right" %>
	    </div>
	</div>
</div>