config/routes.rb
Rails.application.routes.draw do
  
  namespace :admins do
  end
  devise_for :admins, :controllers => {
    :sessions => 'admins/sessions'
  }
  devise_for :customers, :controllers => {
        :sessions => 'customers/sessions',
        :registrations => 'customers/registrations'
  }
  
  scope module: :customers do
    root "homes#top"
    get "homes/about" => "homes#about"
    # 商品
    resources :items, only: [:show, :index]
    get 'genres/:id/genre_items' => 'items#genre_items'
    # 注文
    get "orders/confirm_order" => "orders#confirm_order"
    get "orders/thanks" => "orders#thanks"
    resources :orders, only: [:new, :show, :create, :index]
    # 会員
    get "confirm" => "customers#confirm"
    patch 'customers/withdraw' => 'customers#withdraw', as: 'customers_withdraw'
    resources :customers, only: [:show, :edit, :update]
    # カート
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:create, :index, :update, :destroy]
    # 登録先住所
    resources :addresses, only: [:new, :create, :edit, :update, :destroy]
  end
  
  namespace :admins do
    # 商品
    resources :items, only: [:new, :show, :create, :edit, :index, :update]
    # 注文
    get "/admin" => "homes#top"
    patch "orders/sales_order_status" => "orders#sales_order_status_update"
    patch "orders/production_status" => "orders#production_status_update"
    resources :orders, only: [:show, :index]
    # ジャンル
    resources :genres, only: [:create, :index, :update, :edit]
    # カート
    resources :cart_items, only: [:update]
    # 会員
    resources :customers, only: [:show, :index, :edit, :update, :destroy]
    # 検索
    get 'search' => 'searches#search'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_items
    belongs_to :customer
    has_many :addresses
    
    OrderItem.all.sum(:price)
    enum sales_order_status:{入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4}
end

app/controllers/admins/orders_controller.rb
class Admins::OrdersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @orders = Order.page(params[:page]).per(10)
  end

  def show
    @order = Order.find(params[:id])
    @order_items = @order.order_items.all
    # 下記３行は商品合計を出すため
    @sum = 0
    @subtotals = @order_items.map { |order_item| order_item.price * order_item.amount }
    @sum = @subtotals.sum
  end

  # 実装不可でした。
  def sales_order_status_update
    @order = Order.find(params[:order][:id])
    @order.update(order_params)
    flash[:success] = "注文ステータスを更新しました"
    # sales_order_status_is_deposited?(@order)
    redirect_to admins_order_path(@order)
  end

  # 実装不可でした。
  def production_status_update
    @order_item = OrderItem.find(params[:order_item][:id])
    @order_item.update(order_item_params)
    flash[:info] = "製作ステータスを更新しました"
    redirect_to admins_order_path(@order_item.order_id)
  end

  private

  def order_params
    params.require(:order).permit(:sales_order_status)
  end

  def order_item_params
    params.require(:order_item).permit(:production_status)
  end

  # 以下２つは、update時formから送られてくる値がデフォルトでstringなのでintegerに変換するためのもの。まずはそもそも整数にできるか調べる（Integer()で変換できれば数値、例外発生したら違う）
  # def integer_string?(str)
  #   Integer(str)
  #   true
  # rescue ArgumentError
  #   false
  # end

  # def params_int(order_params)
  #   order_params.each do |key, value|
  #     if integer_string?(value)
  #       order_params[key] = value.to_i
  #     end
  #   end
  # end

  # # 注文ステータスが「入金確認」になったら紐づく製作ステータス全てを「製作待ち」に自動更新
  # def sales_order_status_is_deposited?(order)
  #   if order.sales_order_status_before_type_cast == 1
  #     orderorder_items.each do |p|
  #       p.update(item_sales_order_status: 1)
  #     end
  #     flash[:info] = "製作ステータスが「製作待ち」に更新されました"
  #   end
  # end

  # # 製作ステータスが全部「製作完了」になったら注文ステータスが「発送準備中」に自動更新
  # def item_sales_order_status_is_production_complete?(order)
  #   if  order.order_item.all? do |p|
  #         p.item_sales_order_status_before_type_cast == 3
  #       end
  #     order.update(sales_order_status: 3)
  #     flash[:success] = "注文ステータスが「発送準備中」に更新されました"
  #   end
  # end

  # # 製作ステータスが一つでも「製作中」になったら注文ステータスが「製作中」に自動更新
  # def item_sales_order_status_is_in_production?(order_item)
  #   if item_sales_order.item_sales_order_status_before_type_cast == 2
  #     order_item.order.update(sales_order_status: 2)
  #     flash[:success] = "注文ステータスが「製作中」に更新されました"
  #   end
  # end
end

app/controllers/customers/orders_controller.rb
class Customers::OrdersController < ApplicationController
  
  before_action :authenticate_customer!
  
  def new
    @order = Order.new
    @orders = current_customer.cart_items
    @customer = Customer.find(current_customer.id)
    @addresses = @customer.addresses
    @order.save
  end
  
  def show
    @order = Order.find(params[:id])
    @order.freight = 800
    @order_items = @order.order_items.all
  end
  
  def create
    @order = Order.new(order_params)
    @order.save
    current_customer.cart_items.each do |cart_item|
      @order_items = OrderItem.new
      @order_items.amount = cart_item.amount
      @order_items.item_id = cart_item.item_id
      @order_items.order_id = @order.id
      @order_items.price = cart_item.item.price
      @order_items.production_status = 1
      @order_items.save
    end
    @cart_items = current_customer.cart_items
    @cart_items.destroy_all
    redirect_to orders_thanks_path
  end
  
  def index
    @orders = current_customer.orders
  end
  
  def confirm_order
    @orders = current_customer.orders
    @cart_items = current_customer.cart_items
    @sum = @cart_items.sum{|ci| ci.item.price * ci.amount}
    @order = Order.new(order_params)
    @address = Address.all
    
    if params[:selected_address] == "radio1"
      @order.address = current_customer.address
      @order.postal_code = current_customer.postal_code
      @order.name = current_customer.last_name + current_customer.first_name
    elsif params[:selected_address] == "radio2"
      @order.address = Address.find_by(params[:order][:address_for_order]).address
      @order.postal_code = Address.find_by(params[:order][:address_for_order]).postal_code
      @order.name = Address.find_by(params[:order][:address_for_order]).name
    else
      @order = Order.new(order_params)
      @order.save
      
    end
    
  end
  
  def thanks
  end
  
  private
  
  def order_params
    params.require(:order).permit(
      :payment_method, 
      :postal_code, 
      :address,
      :name,
      :customer_id,
      :freight,
      :billing_amount,
      :sales_order_status
    )
  end
  
  def order_item_params
    params.require(:order_item).permit(:order_id, :item_id, :amount, :production_status, :price)
  end
  
  def address_params
      params.require(:address).permit(:postal_code, :address, :name, :id)
      
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admins/orders/show.html.erb
<div class="row">
  <h2>注文履歴詳細</h2>
  <div style="margin-top: 50px;">
    <table class="table">
      <tbody>
        <tr>
          <th scope="row">購入者</th>
          <td><%=link_to @order.customer.first_name + @order.customer.last_name , admins_customer_path(@order.customer.id) %></td>
        </tr>
        <tr>
          <th scope="row">配送先</th>
          <td>
            <p><%= @order.postal_code %><%= @order.address %></p>
            <p><%= @order.name %></p>
          </td>
        </tr>
        <tr>
          <th scope="row">支払方法</th>
          <td><%= @order.payment_method %></td>
        </tr>
        <tr>
          <th scope="row">注文ステータス</th>
          <td>
            <%= form_with(model: @order, url: admins_orders_sales_order_status_path(@order), method: :patch, local: true) do |f| %>
              <%= f.select :order_status, Order.sales_order_statuses.keys.to_a, {} %>
              <%= f.hidden_field :id, :value => @order.id %>
              <%= f.submit "更新",class:"btn btn-primary" %>
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <div class="col-xs-8"style="margin-top: 50px;">
    <table class="table table-bordered">
      <thead>
        <tr class="table-head" style="background-color:#F5F5F5;">
          <th scope="col">商品名</th>
          <th scope="col">単価（税込）</th>
          <th scope="col">数量</th>
          <th scope="col">小計</th>
          <th scope="col">製作ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @order_items.each do |order_item| %>
          <tr>
            <td><%= order_item.item.name %></td>
            <td><%= order_item.price %></td>
            <td><%= order_item.amount %></td>
            <td><%= order_item.price * order_item.amount %></td>
            <td>
               <%= form_with(model: order_item, url: admins_orders_production_status_path, method: :patch, local: true) do |f| %>
                <%= f.select :sales_order_status, [["着手不可", 0], ["製作待ち", 1], ["製作中", 2], ["製作完了", 3]] ,selected: order_item.production_status_before_type_cast %>
                <%= f.hidden_field :id, :value => order_item.id %>
                <%= f.hidden_field :order_id, :value => @order.id %>
                <%= f.submit "更新",class:"btn btn-primary" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="col-xs-4"style="margin-top: 120px;">
    <table class="table">
      <tbody>
        <tr>
          <th scope="row">商品合計</th>
          <td><%= @sum %></td>
        </tr>
        <tr>
          <th scope="row">送料</th>
          <td><%= @order.freight %></td>
        </tr>
        <tr>
          <th scope="row">請求金額合計</th>
          <td><%= @sum + @order.freight %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>